language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
addons:
  apt:
    sources:
      - fish-shell/release-2
    packages:
      - bash
      - zsh
      - fish
      - tcsh
env:
  - FUNCTIONAL=true BARE=true
install:
  - pip install coveralls
  - pip install -r requirements.txt
  - python setup.py develop
  - rm -rf build
script:
  - export COVERAGE_PYTHON_VERSION=python-${TRAVIS_PYTHON_VERSION:0:1}
  - coverage run --source=thefuck,tests -m py.test -v --capture=sys
after_success: coveralls
